# Generated by Django 4.0.1 on 2022-02-07 20:03

import contact.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_usercontactmodel_delete_usercontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=contact.models.getimagepath),
        ),
        migrations.AddField(
            model_name='usercontactmodel',
            name='webiste',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers. Up to 15 digits allowed.', regex='^\\+?1?\\d{2,15}$')]),
        ),
    ]
