# Generated by Django 4.0.1 on 2022-02-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_usercontactmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontactmodel',
            old_name='webiste',
            new_name='website',
        ),
    ]
