# Generated by Django 4.0.1 on 2022-02-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_webiste_usercontactmodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
