# Generated by Django 4.0.1 on 2022-02-10 16:06

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_usercontactmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactmodel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, default='contact/images/default.png', null=True, upload_to=contact.models.getimagepath),
        ),
        migrations.AlterField(
            model_name='usercontactmodel',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
