# Generated by Django 4.0.1 on 2022-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_usercontactmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
