# Generated by Django 4.0.1 on 2022-02-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_usercontactmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactmodel',
            name='website',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
